on: [push, pull_request]
name: Tests and code
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: juampynr/drupal8ci:latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build project
        run: |
          robo job:build-project
      - name: Build artifact
        run: |
          robo job:build-artifact
      - name: Save artifact
        uses: actions/upload-artifact@v1
        with:
          name: project
          path: project.tar.gz
